export default {
  sameUser: 'You cant add yourself as a friend',
  youCantDeleteYourself: 'You cant delete yourself.',
  found: 'Found',
  pageNotFound: 'Page not found.',
  notFound: 'Not found',
  noRecord: 'No record',
  noRequest: 'No request',
  noToken: 'No token',
  incorrectToken: 'Incorrect Token',
  welcome: 'Welcome',
  successful: 'successful',
  wrongPassword: 'Wrong Password',
  wrongUsernameOrPassword: 'Wrong Username or Password',
  registerSuccess: 'Register Successful',
  thisEmail: 'This Email',
  thisUsername: 'This Username',
  wasCreated: ' was created',
  wasUpdated: ' was updated',
  wasDeleted: ' was deleted',
  alreadyHave: 'is already have',
  cantEmpty: 'It can not be empty!',
  fillRequiredfields: 'Please Fill The Required Fields!',
  alreadyFriends: 'You are already friends!',
  alreadySentARequest: 'You are already sent a friend request!',
  successFriendshipRequest: 'Friendship request was successfully sent.',
  acceptedFriendRequest: 'Friend Request was accepted successfully.',
  friendDeleted: 'Friend delete process successfully done.',
  youDonthavePermissionTo: 'You dont have permission to ',
  youCanOnlyShareWithYourFriend: 'You can only share with your friend'
}
