export default {
    serverListening: "Server listening at localhost:",
    sameUser: "You can't add yourself as a friend",
    found: "Found",
    pageNotFound: "Page not found.",
    notFound: "Not found",
    noRecord: "No record",
    noRequest: "No request",
    noToken: "No token",
    welcome: "Welcome",
    wrongPassword: "Wrong Password",
    registerSuccess: "Register Successful",
    thisEmail: "This Email",
    thisUsername: "This Username",
    noteWasCreated: "Note was created",
    noteWasUpdated: "Note was updated",
    noteWasDeleted: "Note was deleted",
    alreadyHave: "is already have",
    cantEmpty: "It can not be empty!",
    fillRequiredfields: "Please Fill The Required Fields!",
    alreadyFriends: "You are already friends!",
    alreadySentARequest: "You are already sent a friend request!",
    successFriendshipRequest: "Friendship request was successfully sent.",
    acceptedFriendRequest: "Friend Request was accepted successfully.",
    friendDeleted: "Friend delete process successfully done."
};